parse post body

diff --git a/cgi/fcgi b/cgi/fcgi
--- a/cgi/fcgi
+++ b/cgi/fcgi
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
 
-# --Output standard file header
-echo "Content-Type: text/html; charset=UTF-8"
-echo
+# --print standard file header
+echo -e "Content-Type: text/html; charset=UTF-8\n"
+
+# --display error msg and terminate
+function perror() {
+    # print error msg on page
+    echo "<center><h4>ERROR</h4><p>$*</p></center>"
+
+    # clear the post body
+    cat >/dev/null
+
+    # terminate response
+    exit 1
+}
 
 # --fastcgi params list
 #
@@ -32,81 +43,77 @@ echo
 # fastcgi_param REMOTE_USER         $remote_user;
 # fastcgi_param PATH_INFO           $1;
 
-# --save the request body
-REQUEST_BODY="$(cat)"
+# --pasrse request params
+#   need bash v4.0+
+declare -A uparam
 
 # --decode query param value
 function urldecode() {
     : "${*//+/ }"
     echo -e "${_//%/\\x}"
 }
-
-# --pasrse qurey params
-# need bash v4.0+
-declare -A uparam
+# --parse query string params
 function parseQuery() {
-    local body
-    if [ "$CONTENT_TYPE" = 'application/x-www-form-urlencoded' ]; then
-        body=$REQUEST_BODY
-    fi
-    while IFS='=' read -r -d '&' key value; do
-        if [ -n "$key" ]; then
-            uparam["$key"]=$(urldecode "$value")
-        fi
-    done <<<"$QUERY_STRING&$body&"
+    while
+        IFS='=' read -r -d '&' key value
+        [ -n "$key" ]
+    do
+        uparam["$key"]=$(urldecode "$value")
+    done
 }
-parseQuery
+parseQuery <<<"$QUERY_STRING"
 
-# --read post body
+# --pasrse post body params
 function readBody() {
-    local type boundary
-    IFS=' ;=' read -r type _ boundary _ <<<"$CONTENT_TYPE"
-    if [ "$type" = 'multipart/form-data' ]; then
-        local name filename ctype clines
-        while read -r line; do
-            if [[ "$line" =~ ^--${boundary}.* ]]; then
-                if [ -n "$name" ]; then
-                    #            if [ "$ctype" ]; then
-                    #
-                    #            fi
-                    # save form param:
-                    #            uparam[${name//\"/}]=$clines
-                    #            image/gif
-                    #            image/jpeg
-                    #            echo "filename: $filename"
-                    #            echo "ctype: $ctype"
-                    #            echo "clines: $clines"
-
-                    # clear
-                    clines=''
+    IFS=' ;=' read -r type _ boundary <<<"$CONTENT_TYPE"
+    if [ "$type" = 'application/x-www-form-urlencoded' ]; then
+        parseQuery
+    elif [ "$type" = 'multipart/form-data' ]; then
+        while read -r -d $'\r' line; do
+            if [[ "$line" =~ ^--$boundary ]]; then
+                # parse next tow lines
+                IFS=' :;=' read -r -d $'\r' _ disposition _ name _ filename || break # stop when no more lines
+                IFS=' :' read -r -d $'\r' _ ctype # may be a blank line or content type line
+                # formate names
+                name=${name//[\\:\/\"\']/}
+                filename=${filename//[\\:\/\"\']/}
+                # check attr file type
+                if [[ -n "$ctype" ]]; then
+                    if [[ -n "$filename" && ! "$ctype" =~ ^text/ ]]; then
+                        perror "text attr file only, current: [$ctype] [$filename]"
+                    fi
+                    read -r -d $'\r' _ # skip blank line when have content type line
                 fi
-                IFS=' :;=' read -r _ _ _ name _ filename
-                IFS=' :' read -r _ ctype
-                if [ -n "$ctype" ]; then
-                    read -r _
-                fi
-#            else
-#                clines="$clines$line"
+                # set param value from next line
+                read -r -d $'\r' uparam[$name]
+            else
+                # append multi-lines value
+                uparam[$name]=${uparam[$name]}$'\n'$line
             fi
-            ((i++))
-        done <<<"$REQUEST_BODY"
+        done
     fi
 }
-echo "<pre>"
 readBody
-echo "</pre>"
 
 # --test
 #parseQuery "client=firefox-b-d&ei=sT7fX5CPAYfahwPWsJko&q=bash+%E5%B0%86%E5%8F%98%E9%87%8F%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6&oq=bash+%E5%B0%86%E5%8F%98%E9%87%8F%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6&gs_lcp=CgZwc3ktYWIQA1D152pYrLhrYPa5a2gAcAB4AIABtjyIAd9ekgENMy0xLjEuMC4xLjktMpgBAKABAaoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjQq-KSw9ztAhUH7WEKHVZYBgUQ4dUDCAw&uact=5"
+echo "<pre>"
+for key in ${!uparam[*]}; do
+    echo "$key: ${uparam[$key]}"
+done
+echo "</pre>"
+
 cat <<EOF
 <div style='background-color: #71f5f5; border: #999 solid 1px; padding: 5px;'>
 <p>query_string: $QUERY_STRING</p>
 <p>uparam names: ${!uparam[*]}</p>
 <p>content_type: $CONTENT_TYPE</p>
+<p>content_length: $CONTENT_LENGTH</p>
 <p>body: $body</p>
 <p>type: $type</p>
 <p>boundary: $boundary</p>
 <p>post body: <br/>
+<pre>$REQUEST_BODY</pre>
 </p>
 </div>
 EOF
