01/04/2021 1.Solve the problem of special characters and variable references in HTML template files; 2.Can edit blog; 3.Can remove blog;
01/03/2021
1.Plus user blog count after a new blog saved success;
2.Add back/close link when error ocurse;
3.Response buffer is composed of three parts: $RESCODE+$RESHEAD+$RESBODY;

01/02/2021
1.The user blog is counted to a file, obtain id for new blog from it;
2.Save new blog to draft file;
3.Add author and date for blog;

01/01/2021
1.Add admin page and can add a new blog;

diff --git a/cgi/util/common b/cgi/util/common
--- a/cgi/util/common
+++ b/cgi/util/common
@@ -1,71 +1,101 @@
 #!/usr/bin/env bash
 
 # blog common functions
+# Dependent files:
+#       ./http
+# NOTE: should be sourced once at any cgi interface
 # NOTE: all of functions must called in main shell,
 #       and the result is $RET.
 #       because error check in function,
 #       and terminate response directly when error ocurse.
 
-. ./util/http
-
 # --directories
 cgidir=$(dirname "$0")
 rootdir=$(dirname "$cgidir")
 blogsdir="$rootdir/blogs"
-mkdir -p "$blogsdir"
+configdir="$blogsdir/config"
+totalfile="$configdir/total"
+mkdir -p "$configdir"
+if [ ! -e "$totalfile" ]; then
+    echo "all 0" >"$totalfile"
+fi
 
 # --check current user
 function curUser() {
     if [ -z "$REMOTE_USER" ]; then
-        perror 'Current user is empty.'
+        resErr 'Current user is empty.'
     fi
     RET=$REMOTE_USER
 }
 
-# --get current blog file
+# --get current user's file
+#   if file does not exsit, copy templ file to it
+#   if file cannot be write, print error msg and terminate
+#   $1  file path
+#   $2  templ path
+#   result is $1
 function curFile() {
     curUser && user=$RET
-    blogfile="$blogsdir/$user.html"
-    if [ ! -e "$blogfile" ]; then
-        if ! cp "$cgidir/templ/blog.html" "$blogfile"; then
-            perror "Can not copy template file to $user's blog file."
+    if [ ! -e "$1" ]; then
+        if ! cp "$2" "$1"; then
+            resErr "Can not copy template file[$2] to $user's file[$1]."
         fi
         # write user name to blog file
-        sed -i "s/<\!--user-->/$user/g" "$blogfile"
+        sed -i "s/<!--user-->/$user/g" "$1"
     fi
-    if [ ! -w "$blogfile" ]; then
-        perror "Can not write to $user's blog file."
+    if [ ! -w "$1" ]; then
+        resErr "Can not write to $user's file[$1]."
     fi
-    RET=$blogfile
+    RET=$1
 }
 
-# --get max id for current user
-function maxId() {
-    curFile && file=$RET
-    RET=$(sed -n "/^<\!--new-blog-->/{n; s/^<li id='\([0-9]*\)'.*/\1/p}" "$file")
+# --get current user's draft file
+#   result is draft file path
+function draftFile() {
+    curUser && user=$RET
+    curFile "$blogsdir/${user}_draft.html" "$cgidir/templ/draft.html"
 }
 
-# --create a blog node in blog file
-#   the id = maxId + 1
+# --get next blog id for current user
+#   $1  true: update user blog max id into $totalfile
+function nextId() {
+    curUser && user=$RET
+    RET=$(sed -n "s/^$user \([0-9]*\).*/\1/p" "$totalfile")
+    if [ -n "$RET" ]; then
+        RET=$(($RET + 1))
+        [ "$1" = true ] && sed -i "/^$user /c $user $RET" "$totalfile"
+    else
+        RET=1
+        [ "$1" = true ] && sed -i "\$a$user $RET" "$totalfile"
+    fi
+    return 0 # this statement must be included to ensure filling of the return value $RET
+}
+
+# --create a new blog node for draft file
 #   the title and content will be auto encode
-#   $1      title
-#   $2      content
+#   $1      id
+#   $2      title
+#   $3      content
+#   $4      create time(tc) for remkae blog
 function mkBlog() {
     if [ -z "$1" ]; then
-        perror 'Blog title can not be empty.'
+        resErr 'Blog id can not be empty.'
     fi
     if [ -z "$2" ]; then
-        perror 'Blog content can not be empty.'
+        resErr 'Blog title can not be empty.'
     fi
-    maxId && id=$((${RET:-0} + 1))
-    date=$(date +%s)
-    date2=$(date "+%H:%M:%S %m/%d/%Y")
-    htmlEncode "$1" && title=$RET
-    htmlEncode "$2" && content=$RET
+    if [ -z "$3" ]; then
+        resErr 'Blog content can not be empty.'
+    fi
+    curUser && user=$RET
+    ndate=$(date +%s)
+    sdate=$(date "+%H:%M:%S %m/%d/%Y")
+    htmlEncode "$2" && title=$RET
+    htmlEncode "$3" && content=$RET
     IFS= read -r -d '' RET <<EOF
-<li id='$id' publish='0' date='$date'>
+<li id='$1' tc='${4:-$ndate}' tu='$ndate'>
 <p>$title</p>
-<p>$date2</p>
+<p>$user $sdate</p>
 <pre>$content</pre>
 <ul>
 <!--new-reply-->
@@ -75,31 +105,145 @@ EOF
     return 0 # this statement must be included to ensure filling of the return value $RET
 }
 
-# --get my blog list
-function getList() {
-    curFile && file=$RET
-    RET="$(sed -n "/^<li id='/{s/^<li id='\([0-9]*\)' publish='\(.*\)' date='\(.*\)'.*/\1 \2 \3/p; n; s/^<p>\(.*\)<\/p>/\1/p; n; s/^<p>\(.*\)<\/p>/\1/p}" "$file")"
+# --remove blog in draft
+#   $1      blog id
+#   $RET is blog first line number
+function rmBlog() {
+    if [ -z "$1" ]; then
+        resErr 'Blog id can not be empty.'
+    fi
+    # remove blog in draft file
+    draftFile && file=$RET
+    # get first line number by blog id
+    RET=$(sed -n "/^<li id='$1'/=" "$file")
+    if [ -z "$RET" ]; then
+        resErr "Can not find blog by id($1)."
+    fi
+    # delete blog lines
+    sed -i "$RET,/^<\/li>$/d" "$file"
 }
 
-# --make html for my blog list
-function mkList() {
-    getList && list=$RET
+# --save blog to draft
+#   $1      blog id
+#     == NULL   save as new blog
+#     != NULL   edit blog by id
+#   $2      title
+#   $3      content
+#   $RET is blog id
+function draftSave() {
+    # save blog to draft file
+    draftFile && file=$RET
+    # new blog
+    if [ -z "$1" ]; then
+        # get id for new blog
+        nextId && id=$RET
+        # make blog html node
+        mkBlog "$id" "$2" "$3" && blog=$RET
+        # insert new blog text into draft file
+        if sed -i "/^<!--new-draft-->/r"<(echo -n "$blog") "$file"; then
+            # generate next id for current user when success
+            nextId true
+            RET=$id
+            return 0
+        else
+            return 1
+        fi
+    else # edit blog
+        # get first line number and tc by blog id
+        IFS=$'\n' read -r -d '' ln tc <<<"$(sed -n "/^<li id='$1'/{=; s/.*tc='\([0-9]*\)'.*/\1/p}" "$file")"
+        if [ -z "$ln" ]; then
+            resErr "Can not find blog by id($1)."
+        fi
+        # remake blog html node
+        mkBlog "$1" "$2" "$3" "$tc" && blog=$RET
+        # remove old blog
+        rmBlog "$1" && ln=$(($RET-1))
+        # insert new blog at the original location
+        if sed -i "${ln}r"<(echo -n "$blog") "$file"; then
+            RET=$1
+            return 0
+        else
+            return 1
+        fi
+    fi
+}
+
+# --get blog list
+#   $1      which file: draft or blog
+function getList() {
+    if [ -z "$1" ]; then
+        resErr 'File is empty when get blog list.'
+    fi
+    RET="$(sed -n "/^<li id='/{ \
+    s/^<li id='\([0-9]*\)' tc='\([0-9]*\)' tu='\([0-9]*\)'.*/\1 \2 \3/p; \
+    n; s/^<p>\(.*\)<\/p>/\1/p; \
+    n; s/^<p>\(.*\)<\/p>/\1/p \
+    }" "$1")"
+}
+
+# --make html for draft list
+function draftList() {
+    draftFile && file=$RET
+    getList "$file" && list=$RET
     RET=''
     while
-        IFS=' ' read -r id publish date
+        IFS=' ' read -r id tc tu
         [ -n "$id" ]
     do
-        [ "$publish" = 0 ] && p_='Saved' || p_='Published'
         IFS= read -r title
-        IFS= read -r date2
+        IFS=' ' read -r user time date
         IFS= read -r -d '' line <<EOF
 <li>
-<span class='id'>$id</span>
-<span class='date'>$date2</span>
-<span class='publish'>$p_</span>
-<a href='edit?id=$id' target='_blank'>$title</a>
+<span>$id</span>
+<span>$time $date</span>
+<a href='#' onclick='window.open("edit?id=$id")'>$title</a>
 </li>
 EOF
-        RET=$RET$'\n'$line
+        RET=$RET$line
     done <<<"$list"
+}
+
+# --get blog content
+#   $1      which file: draft or blog
+#   $2      blog id
+function getContent() {
+    if [ -z "$1" ]; then
+        resErr 'File is empty when get blog content.'
+    fi
+    if [ -z "$2" ]; then
+        resErr 'Blog id is empty when get blog content.'
+    fi
+    # get first line number by blog id
+    ln=$(sed -n "/^<li id='$2'/=" "$1")
+    if [ -z "$ln" ]; then
+        resErr "Can not find blog by id($1)."
+    fi
+    RET="$(sed -n "$ln{ \
+    s/^<li id='\([0-9]*\)' tc='\([0-9]*\)' tu='\([0-9]*\)'.*/\1 \2 \3/p; \
+    n; s/^<p>\(.*\)<\/p>/\1/p; \
+    n; s/^<p>\(.*\)<\/p>/\1/p; \
+    n; \
+    s/^<pre>\(.*\)<\/pre>$/\1/p; t; \
+    s/^<pre>\(.*\)/\1/p; \
+    :jc \
+    n; \
+    s/\(.*\)<\/pre>$/\1/p; t; \
+    p; b jc; \
+    }" "$1")"$'\r' # Add end mark to avoid ending newline when reading
+}
+
+# --get blog content for edit in draft
+#   $1      blog id
+#   multiple return values
+function draftBlog() {
+    draftFile && file=$RET
+    getContent "$file" "$1" && blog=$RET
+    if
+        IFS=' ' read -r id tc tu
+        [ -n "$id" ]
+    then
+        IFS= read -r title
+        IFS=' ' read -r user time date
+        IFS= read -r -d $'\r' content
+    fi <<<"$blog"
 }
diff --git a/cgi/util/http b/cgi/util/http
--- a/cgi/util/http
+++ b/cgi/util/http
@@ -1,26 +1,103 @@
 #!/usr/bin/env bash
 
 # http common functions
+# Dependent files:
+#       no dependent
+# NOTE: should be sourced once at any cgi interface
+#       in order to ensure that the trap event is valid,
+#       please sourced it first
 # NOTE: all of functions must called in main shell,
 #       and the result is $RET.
 #       because error check in function,
 #       and terminate response directly when error ocurse.
 
-# --html encoding
-function htmlEncode() {
-    RET=$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g' <<<"$*")
-}
-
-# --display error msg and terminate
-function perror() {
-    htmlEncode "$*" && html=$RET
-    RET="<center><h4>ERROR</h4><p>$html</p></center>"
-    # print error msg on page
-    echo "$RET"
-
-    # clear the post body
+# --make response
+#   $RESCODE+$RESHEAD+$RESBODY is all response buffer for one rquest
+RESCODE=''
+RESHEAD=''
+RESBODY=''
+# trap exit event to send response buffer
+function onExit() {
+    # clear the request post body first
     cat >/dev/null
+
+    # ouput response buffer
+    echo "$RESCODE"
+    echo "$RESHEAD"
+    echo -n "$RESBODY"
+}
+trap onExit EXIT
+# set response code
+#   $1  code
+#   $2  descript
+function resCode() {
+    printf -v RESCODE 'HTTP/1.1 %s %s' "$1" "$2"
+    RESHEAD=''
+    RESBODY=''
+}
+# set response header
+#   $1  name
+#   $2  value
+function resHead() {
+    printf -v RESHEAD '%s%s: %s\n' "$RESHEAD" "$1" "$2"
+}
+# append reponse body
+#   $1  text to append to reponse body
+function resBody() {
+    RESBODY=$RESBODY$1
+}
+# reponse 200
+function res200() {
+    resCode 200 'OK'
+    resHead 'Content-Type' 'text/html; charset=UTF-8'
+}
+# response 301
+#   $1  relocation url
+function res301() {
+    resCode 301 'Moved Permanently'
+    resHead 'Location' "$1"
+}
+# response a html template file
+# support var expand
+#   $1  file path
+function resFile() {
+    if [ -z "$1" ]; then
+        resErr 'File is empty when response a html template file.'
+    fi
+    # More difficult here
+    # Use single quotes to avoid bash string escaping
+    # NOTE: the sed regular expression escaping
+    html=$(sed 's/\(\\\)\([^$]\)/\1\1\2/g; s/"/\\"/g; s/`/\\`/g;' "$1")
+    resBody "$(eval echo -n "\"$html\"")"
+}
+# response error and terminate
+#   $ERRCLOSE == true render close button on error screen
+#   $ERRCLOSE == false render back button on error screen
+function resErr() {
+    htmlEncode "$*" && html=$RET
+
+    if [ "$ERRCLOSE" = true ]; then
+        errBtn="<a href='#' onclick='window.close()'>CLOSE</a>"
+    else
+        errBtn="<a href='#' onclick='history.back()'>BACK</a>"
+    fi
+
+    # set error msg as reponse body
+    RESBODY="<div style='width=100%; height=100%; text-align: center;'> \
+    <h4>ERROR</h4> \
+    <p>$html</p> \
+    <p>$errBtn</p> \
+    </div>"
 
     # terminate response
     exit 1
+}
+
+# --html encoding
+function htmlEncode() {
+    RET=$(sed "s/\&/\&amp;/g; \
+    s/</\&lt;/g; \
+    s/>/\&gt;/g; \
+    s/\"/\&quot;/g; \
+    s/'/\&#39;/g" <<<"$*")
 }
